### ISSUE TITLE
Error in : package or namespace load failed for 'RLumShiny'

### ISSUE THREAD

**Issue by wanqiangdehuoguo** [tzerk/RLumShiny#14] opened 2021-11-01 07:25 UTC
i am trying to deploy my Shiny software on a server. And I encountered an error while loading RLumShiny. I have installed the package RLumShiny on the server. When i use root run R: 
```
> library(RLumShiny)
Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'
```
When i use shiny(Not root user) run R:
```
su -m - shiny
R
> library(RLumShiny)
Error: package or namespace load failed for 'RLumShiny' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/shiny/R/x86_64-redhat-linux-gnu-library/4.1/terra/libs/terra.so':
  /home/shiny/R/x86_64-redhat-linux-gnu-library/4.1/terra/libs/terra.so: invalid ELF header
```
And when i run my shiny app, i found that ShinyApp could not be opened and the same error message appeared in the log file, Here's the log information:
```
su: ignoring --preserve-environment, it's mutually exclusive with --login
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
6: Setting LC_PAPER failed, using "C" 
7: Setting LC_MEASUREMENT failed, using "C" 

Listening on http://127.0.0.1:42011

Attaching package: 'jsonlite'

The following object is masked from 'package:shiny':

    validate

Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'


su: ignoring --preserve-environment, it's mutually exclusive with --login
su: ignoring --preserve-environment, it's mutually exclusive with --login
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
6: Setting LC_PAPER failed, using "C" 
7: Setting LC_MEASUREMENT failed, using "C" 

Listening on http://127.0.0.1:42011

Attaching package: 'jsonlite'

The following object is masked from 'package:shiny':

    validate

Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'

Welcome to googleVis version 0.6.10

Please read Google's Terms of Use
before you start using the package:
https://developers.google.com/terms/

Note, the plot method of googleVis will by default use
the standard browser to display its output.

See the googleVis package vignettes for more details,
or visit https://github.com/mages/googleVis.

To suppress this message use:
suppressPackageStartupMessages(library(googleVis))

Warning: Error in : package or namespace load failed for 'RLumShiny' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/shiny/R/x86_64-redhat-linux-gnu-library/4.1/terra/libs/terra.so':
  /home/shiny/R/x86_64-redhat-linux-gnu-library/4.1/terra/libs/terra.so: invalid ELF header
  76: stop
  75: value[[3L]]
  74: tryCatchOne
  73: tryCatchList
  72: tryCatch
  71: library
```
Could you tell me how can i fix it?

**Comment by RLumSK** [comment] 2021-11-01 11:10
@wanqiangdehuoguo To me, it looks not like a problem with `RLumShiny` but with your R installation. 

>  library(RLumShiny)
Error: package or namespace load failed for 'RLumShiny' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/shiny/R/x86_64-redhat-linux-gnu-library/4.1/terra/libs/terra.so':
  /home/shiny/R/x86_64-redhat-linux-gnu-library/4.1/terra/libs/terra.so: invalid ELF header

This message above tells you that the library from the package `terra` could not be loaded due to an invalid
header (not sure, perhaps some linking of the libraries failed). This has, however, nothing to do with `shiny` or even `RLumShiny`. Have you tried re-installing the package in question (`terra`) manually in your R session and load it? 

```r 
install.packages("terra")
library(terra)
```

Either way, it is not a bug in `RLumShiny` and so I close this ticket. If you believe that it actually is a bug in `RLumShiny` please feel free to reopen the ticket.

**Closed by RLumSK** 2021-11-01 11:10 UTC

**Comment by RLumSK** [comment] 2021-11-08 19:14
@wanqiangdehuoguo Supplement, for what it is worth, I now encountered a similar issue in our Ubuntu CI. While my answer still stands, now we know where the package `'terra'` comes from: 

> -raster now imports terra (instead of the other way around) [...]
(https://cran.r-project.org/web/packages/raster/NEWS)

`'Luminescence'` imports `'raster'` and '`RLumShiny'` imports `'Luminescence'` as an essential package.

**Comment by wanqiangdehuoguo** [comment] 2021-11-09 09:56
Sincerely thank you for your reply，
I encountered this problem when configuring shiny-Server, and it has been solved after repeated attempts.
There are two reasons: 

1. I installed the package Terra in the directory of user shiny by mistake, and the operation of the package needs root.

2. Several system libraries are not installed in the centos system of the server

I think it's the same problem in Ubuntu, you need to install with `sudo apt-get`

**Comment by RLumSK** [comment] 2021-11-09 10:06
@wanqiangdehuoguo Thanks and I am glad that it works now. Yes, I also saw yesterday that the `'terra'` package has some external dependencies outside of the usual R environment. 

And thanks for your report, it is always good to know how things were finally solved.
